# Generated by Django 4.0.2 on 2022-06-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_tool_user_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='Software Engineer', max_length=150, verbose_name='Должность'),
        ),
    ]
