# Generated by Django 4.0.2 on 2022-03-18 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Проект')),
                ('type', models.CharField(choices=[('software', 'Разработка программного обеспечения'), ('service_management', 'Управление услугами'), ('work_management', 'Управление работой'), ('marketing', 'Маркетинг'), ('work_with_personnel', 'Работа с кадрами'), ('finance', 'Финансы'), ('design', 'Проектирование'), ('personal', 'Личные')], max_length=50, verbose_name='Тип проекта')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
