# Generated by Django 4.0.2 on 2022-06-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_developers_alter_project_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.CharField(max_length=150, verbose_name='Дедлайн')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='projects.project')),
            ],
            options={
                'verbose_name': 'РоадМэп',
                'verbose_name_plural': 'РоадМэпы',
            },
        ),
    ]
