# Generated by Django 4.0.2 on 2022-03-30 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task', 'Задача'), ('invitation', 'Приглашение'), ('change', 'Изменение'), ('message', 'Сообщение')], default=None, max_length=30, verbose_name='Тип уведомления'),
            preserve_default=False,
        ),
    ]
