# Generated by Django 4.0.2 on 2022-06-02 11:20

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='epic_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.epictask'),
        ),
        migrations.AlterField(
            model_name='task',
            name='type_task',
            field=models.ForeignKey(default=tasks.models.get_default_type_task, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.typetask'),
        ),
    ]
