# Generated by Django 4.0.2 on 2022-06-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_epic_task_alter_task_type_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='epictask',
            name='color',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Цвет эпика'),
        ),
    ]
