# Generated by Django 4.0.2 on 2022-06-14 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_epictask_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadMapTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=150, verbose_name='Описание')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_tasks', to='tasks.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'РоадМэп задачи',
                'verbose_name_plural': 'РоадМэпы задач',
            },
        ),
    ]
