# Generated by Django 4.0.2 on 2022-06-14 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_roadmap'),
        ('tasks', '0006_roadmaptask'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadmaptask',
            name='roadmap',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='roadmaptasks', to='projects.roadmap', verbose_name='Роадмэп'),
            preserve_default=False,
        ),
    ]
