# Generated by Django 4.0.2 on 2022-06-13 13:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_chat_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 13, 47, 2, 15415, tzinfo=utc)),
        ),
    ]
