# Generated by Django 4.0.2 on 2022-06-13 18:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 13, 18, 44, 21, 464720, tzinfo=utc)),
        ),
    ]
