# Generated by Django 4.0.2 on 2022-06-14 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_message_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 14, 11, 45, 46, 756392, tzinfo=utc)),
        ),
    ]
