# Generated by Django 4.0.2 on 2022-04-11 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0002_project_developers_alter_project_manager'),
        ('tasks', '0003_alter_task_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('task', 'Задача'), ('invitation', 'Приглашение'), ('change', 'Изменение'), ('message', 'Сообщение')], max_length=30, verbose_name='Тип уведомления')),
                ('message', models.CharField(blank=True, max_length=150, null=True, verbose_name='Сообщение')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifictions', to='projects.project')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificications', to='tasks.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifictions_to', to=settings.AUTH_USER_MODEL)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifictions_from', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
